dataset:
  n_range: [5]
  N_sym_range: [128]
  N_train: 10000
  mean_length: 40
  rank_range: [16]
  D_range: [16]
  input: /Users/anej/data/artificial_ngrams/representation_datasets/
  output: /Users/anej/data/artificial_ngrams/classic_results_representations/